### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by AjuanLes** [dougg0k/gaming_os_tweaker#19] opened 2023-08-11 09:44 UTC
Before anything I'd like to congratulate you with this tremendous work. I think this is one of the best repositories for tweaks focused on gaming and latency that there's, which hopefully can be seen in some LAN CS tournaments! Make youtube videos dude, you'll explode.

Overall the first experience is great, but raw.

1. The nvidia control panel won't open, with the following message: this app has been blocked by your system administrator
- Is kinda fixable if you get the ownership of nvcplui.exe and make a shortcut. The nvcleaner / DDU methods don't work to reset Nvidia to default behavior (opening panel from desktop, or even start)
2. Previously used USB ports just stopped working for some reason after the tweaks. If I switch to USB ports that weren't used before the tweaks happened - the keyboard and mouse works :D
- EDIT: seems like it's because the devices got deleted and windows driver auto updates were disabled.

**Comment by dougg0k** [comment] 2023-08-11 14:12
Thanks. I dont really care much, but anyone are free to make videos about it, if they want.

1. I suppose I could try to reset the ownership of the ncp and zip it again.
- What do you mean NVCleaner / DDU methods dont work? 
DDU are a clean up tool, so you can install a new driver and NVCleanstall to debloat the driver before installation.

2. USB ports do not get deleted or disabled with the scripts. But tweaks do try to disable any sort of power saving enabled in them.

You can clean up devices that are no longer in use though, with  
https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/cleanup_unused_devices.cmd 

Windows update being disabled doesnt and should not have any relations to it.

**Comment by dougg0k** [comment] 2023-08-11 19:47
I added some instructions in how to deal with the nvcp ownership problem in the tools readme, it should help.

I'm not sure there is anything to be done about the USB issue, nothing is being done to remove or disable it.

I will be closing the issue, if you have any other issues, or find the root cause of your usb problem, you can send a message here about it.

**Closed by dougg0k** 2023-08-11 19:47 UTC
